=== pranavadith7/On-Time-Pharmacy/xml/order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="orders">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="order">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="orderID" type="xs:string" />
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="phone" type="xs:string" />
                            <xs:element name="address" type="xs:string" />
                            <xs:element name="date" type="xs:string" />
                            <xs:element name="medicines">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="medicine" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="medicine_name" type="xs:string" />
                                                    <xs:element name="quantity" type="xs:string" />
                                                    <xs:element name="discount" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="amount" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pranavadith7/On-Time-Pharmacy/xml/order.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE orders SYSTEM "order_type.dtd"> -->
<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="order.xsd">
    <order>
        <orderID>101</orderID>
        <name>Pranav</name>
        <phone>9361213492</phone>
        <address>Ettimadai, Coimbatore</address>
        <date>25/08/2022</date>
        <medicines>
            <medicine>
                <medicine_name>Crocin</medicine_name>
                <quantity>3</quantity>
                <discount>10</discount>
            </medicine>
            <medicine>
                <medicine_name>Gelusil</medicine_name>
                <quantity>1</quantity>
                <discount>15</discount>
            </medicine>
        </medicines>
        <amount>500</amount>
    </order>
</orders>
